"""Gradio web demo for PCB defect detection.

Three tabs:
1. Detect Defects — upload a PCB image, get detection overlay
2. Generate Synthetic — see the ControlNet generation pipeline in action
3. Results — view mAP comparison between real-only and augmented models
"""

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import gradio as gr
from PIL import Image

from src.detection.predict import detect_defects
from src.generation.edge_extraction import extract_canny_edges

# Lazy-loaded models
_detector_model = None
_detector_path = None


def _get_detector(model_path):
    """Cache the YOLO model to avoid reloading."""
    global _detector_model, _detector_path
    if model_path and str(model_path) != _detector_path:
        from ultralytics import YOLO
        _detector_model = YOLO(str(model_path))
        _detector_path = str(model_path)
    return _detector_model


def run_detection(image, confidence, model_path):
    """Run defect detection on uploaded image."""
    if image is None:
        return None, "Please upload a PCB image."
    if model_path is None or not Path(model_path).exists():
        return None, "No model available. Train one with: python scripts/train_detector.py"

    annotated, detections = detect_defects(Path(model_path), image, confidence)

    summary = f"Found {len(detections)} defect(s):\n"
    for d in detections:
        summary += f"  - {d['class']}: {d['confidence']:.2f}\n"

    return annotated, summary


def run_edge_extraction(image):
    """Extract Canny edges from uploaded PCB image."""
    if image is None:
        return None
    return extract_canny_edges(image)


def create_app(model_path=None):
    """Create the Gradio application."""

    with gr.Blocks(
        title="PCB Defect Detection",
        theme=gr.themes.Soft(),
    ) as app:
        gr.Markdown("# PCB Defect Detection with Diffusion-Powered Augmentation")
        gr.Markdown(
            "Upload a PCB image to detect manufacturing defects. "
            "Detection model trained with synthetic data generated by "
            "**Stable Diffusion 1.5 + ControlNet (Canny)**."
        )

        model_path_state = gr.State(str(model_path) if model_path else None)

        with gr.Tabs():
            # Tab 1: Detection
            with gr.Tab("Detect Defects"):
                with gr.Row():
                    with gr.Column():
                        input_image = gr.Image(label="Upload PCB Image", type="pil")
                        confidence = gr.Slider(
                            0.1, 0.9, value=0.25, step=0.05,
                            label="Confidence Threshold",
                        )
                        detect_btn = gr.Button("Run Detection", variant="primary")
                    with gr.Column():
                        output_image = gr.Image(label="Detection Results", type="pil")
                        results_text = gr.Textbox(label="Detections", interactive=False, lines=8)

                detect_btn.click(
                    run_detection,
                    inputs=[input_image, confidence, model_path_state],
                    outputs=[output_image, results_text],
                )

            # Tab 2: Generation Pipeline Visualization
            with gr.Tab("Generation Pipeline"):
                gr.Markdown(
                    "### How Synthetic Data is Generated\n"
                    "1. Take a PCB template image\n"
                    "2. Extract Canny edges (captures trace layout)\n"
                    "3. Feed edges to ControlNet + defect prompt → synthetic defective image\n"
                    "4. Transfer bounding box annotations from original"
                )
                with gr.Row():
                    with gr.Column():
                        gen_input = gr.Image(label="Upload PCB Image", type="pil")
                        edge_btn = gr.Button("Extract Canny Edges", variant="primary")
                    with gr.Column():
                        edge_output = gr.Image(label="Canny Edge Map (ControlNet Input)", type="pil")

                edge_btn.click(run_edge_extraction, inputs=[gen_input], outputs=[edge_output])

            # Tab 3: Results
            with gr.Tab("Results"):
                gr.Markdown("### Model Comparison: Real-Only vs Real + Synthetic Training")
                gr.Markdown(
                    "After training YOLOv8 on both datasets, we compare:\n"
                    "- **mAP50**: Mean Average Precision at IoU 0.5\n"
                    "- **Per-class precision and recall**\n"
                    "- **Confusion matrices**\n\n"
                    "Run `python scripts/evaluate.py` to generate comparison artifacts."
                )

                results_img_path = Path("assets/results_comparison.png")
                if results_img_path.exists():
                    gr.Image(value=str(results_img_path), label="mAP Comparison")
                else:
                    gr.Markdown("*Results will appear here after running the evaluation pipeline.*")

    return app
